using System.Text.RegularExpressions;
using System.Xml.Linq;
using Xunit;

namespace Weir.Tests;

// Guards the admin console's resource catalogue. AdminStrings.Designer.cs is generated by the resx
// designer and checked in, and the ru catalogue is maintained by hand, so the three files drift
// silently: a key added to the resx without regenerating the designer does not compile, but a key
// missing from ru falls back to English at runtime, and a translation that drops a {0} throws only on
// the code path that formats it. These tests turn all of that into a build failure.
public class AdminLocalizationTests
{
    /// <summary>Locates the admin console's Resources folder by walking up to the repo root.</summary>
    /// <returns>The absolute path to <c>src/Weir.Admin/Resources</c>.</returns>
    private static string ResourcesDir()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Weir.slnx")))
        {
            dir = dir.Parent;
        }

        Assert.NotNull(dir);
        var resources = Path.Combine(dir!.FullName, "src", "Weir.Admin", "Resources");
        Assert.True(Directory.Exists(resources), $"Admin resources not found at {resources}.");
        return resources;
    }

    /// <summary>Reads a resx into a key/value map.</summary>
    /// <param name="fileName">The resx file name inside the Resources folder.</param>
    /// <returns>Every string entry in the file, keyed by resource name.</returns>
    private static Dictionary<string, string> ReadResx(string fileName)
    {
        var path = Path.Combine(ResourcesDir(), fileName);
        Assert.True(File.Exists(path), $"{fileName} not found at {path}.");

        return XDocument.Load(path).Root!
            .Elements("data")
            .ToDictionary(
                d => d.Attribute("name")!.Value,
                d => d.Element("value")?.Value ?? string.Empty,
                StringComparer.Ordinal);
    }

    /// <summary>Collects the composite-format placeholders ({0}, {1}, ...) used by a value.</summary>
    /// <param name="value">The resource value to scan.</param>
    /// <returns>The distinct argument indexes referenced, ascending.</returns>
    private static IReadOnlyList<string> Placeholders(string value) =>
        Regex.Matches(value, @"\{(\d+)(?:[,:][^}]*)?\}")
            .Select(m => m.Groups[1].Value)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToList();

    [Fact]
    public void Every_English_Key_Has_A_Russian_Translation()
    {
        var en = ReadResx("AdminStrings.resx");
        var ru = ReadResx("AdminStrings.ru.resx");

        Assert.NotEmpty(en);

        var untranslated = en.Keys.Where(k => !ru.ContainsKey(k)).Order(StringComparer.Ordinal).ToList();
        Assert.True(untranslated.Count == 0, $"Keys missing from AdminStrings.ru.resx: {string.Join(", ", untranslated)}");

        var orphaned = ru.Keys.Where(k => !en.ContainsKey(k)).Order(StringComparer.Ordinal).ToList();
        Assert.True(orphaned.Count == 0, $"Keys in AdminStrings.ru.resx with no English entry: {string.Join(", ", orphaned)}");
    }

    [Fact]
    public void No_Resource_Value_Is_Empty()
    {
        foreach (var file in new[] { "AdminStrings.resx", "AdminStrings.ru.resx" })
        {
            var blank = ReadResx(file)
                .Where(kv => string.IsNullOrWhiteSpace(kv.Value))
                .Select(kv => kv.Key)
                .Order(StringComparer.Ordinal)
                .ToList();

            Assert.True(blank.Count == 0, $"Empty values in {file}: {string.Join(", ", blank)}");
        }
    }

    [Fact]
    public void Translations_Keep_The_Same_Format_Placeholders()
    {
        // A translation that drops or invents a {0} throws FormatException, but only when the code path
        // that formats it runs - which a manual pass through the console will not necessarily reach.
        var en = ReadResx("AdminStrings.resx");
        var ru = ReadResx("AdminStrings.ru.resx");

        var mismatched = en
            .Where(kv => ru.ContainsKey(kv.Key))
            .Where(kv => !Placeholders(kv.Value).SequenceEqual(Placeholders(ru[kv.Key]), StringComparer.Ordinal))
            .Select(kv => $"{kv.Key} (en: {string.Join("/", Placeholders(kv.Value))}, ru: {string.Join("/", Placeholders(ru[kv.Key]))})")
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.True(mismatched.Count == 0, $"Placeholder mismatch between en and ru: {string.Join("; ", mismatched)}");
    }

    [Fact]
    public void English_Values_Are_Keyboard_Only_Ascii()
    {
        // Project rule: authored English text is ASCII. This catches an em-dash or a smart quote pasted
        // into the neutral catalogue. The ru catalogue is exempt - Cyrillic is the point.
        var offenders = ReadResx("AdminStrings.resx")
            .Where(kv => kv.Value.Any(c => c > '~' || (c < ' ' && c is not ('\n' or '\r' or '\t'))))
            .Select(kv => kv.Key)
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.True(offenders.Count == 0, $"Non-ASCII characters in English values: {string.Join(", ", offenders)}");
    }

    [Fact]
    public void Designer_Exposes_A_Property_For_Every_Key()
    {
        // AdminStrings.Designer.cs is generated and checked in. Hand-editing the resx without
        // regenerating it leaves the new key unreachable (or a removed key throwing at runtime).
        var designer = File.ReadAllText(Path.Combine(ResourcesDir(), "AdminStrings.Designer.cs"));

        var declared = Regex.Matches(designer, @"public static string (\w+) \{")
            .Select(m => m.Groups[1].Value)
            .ToHashSet(StringComparer.Ordinal);

        var missing = ReadResx("AdminStrings.resx").Keys
            .Where(k => !declared.Contains(k))
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.True(missing.Count == 0, $"AdminStrings.Designer.cs is stale; regenerate it. Missing: {string.Join(", ", missing)}");

        var stale = declared.Where(p => !ReadResx("AdminStrings.resx").ContainsKey(p)).Order(StringComparer.Ordinal).ToList();
        Assert.True(stale.Count == 0, $"AdminStrings.Designer.cs declares keys the resx no longer has: {string.Join(", ", stale)}");
    }
}
